### PR TITLE
Fix #128

### LINKED ISSUE #128: DHTML is being created (way) too early!
https://github.com/photonle/Photon/blob/development/lua/autorun/photon/cl_photon_hud.lua#L587 this line should be put onto https://wiki.facepunch.com/gmod/GM:OnGamemodeLoaded (or more late hook, such as https://wiki.facepunch.com/gmod/GM:InitPostEntity) hook, instead of attempting to create panel right after hud Lua file is initialized (on autorun, before vgui/gamemode but after include/init.lua)

```
Warning: vgui.Create failed to create the VGUI component (DHTML)

[Photon: Lighting Engine] lua/autorun/photon/cl_photon_hud.lua:304: Panel "DHTML" does not exist.
  1. error - [C]:-1
   2. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:189
    3. unknown - addons/dlib/lua/dlib/luabridge/luabridge.lua:243
     4. ProtectedCall - [C]:-1
      5. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:242
       6. Init - lua/autorun/photon/cl_photon_hud.lua:304
        7. unknown - lua/autorun/photon/cl_photon_hud.lua:585
         8. include - [C]:-1
          9. unknown - lua/autorun/photon/sh_photon_init.lua:104
           10. include - [C]:-1
            11. unknown - lua/autorun/emv_init.lua:12


[Photon: Lighting Engine] addons/dlib/lua/dlib/luabridge/luabridge.lua:247: Cannot create panel "DHTML"! Look for errors above
  1. error - [C]:-1
   2. Create - addons/dlib/lua/dlib/luabridge/luabridge.lua:247
    3. Init - lua/autorun/photon/cl_photon_hud.lua:304
     4. unknown - lua/autorun/photon/cl_photon_hud.lua:585
      5. include - [C]:-1
       6. unknown - lua/autorun/photon/sh_photon_init.lua:104
        7. include - [C]:-1
         8. unknown - lua/autorun/emv_init.lua:12
```

### PR DESCRIPTION
**Pull request by DBotThePony**
This fixes #128 
And cleanup some code.

### CODE REVIEW

File: lua/autorun/photon/cl_photon_hud.lua [hunk 1]
```diff
@@ -46,8 +46,14 @@ Photon.AddCustomHUDIcon = function(name, data)
 	end
 
 	PhotonHUD.Icons[name] = data
-	PhotonHUD:BuildCode()
-	PhotonHUD:Init()
+
+	if PhotonHUD.Code then
+		PhotonHUD:BuildCode()
+	end
```
Comment (JoshPiper) [inline lua/autorun/photon/cl_photon_hud.lua]: Why was this done, when BuildCode() builds and sets .Code?

**Review by JoshPiper — COMMENTED** [review]
Seems fine aside from the one point of confusion.

File: lua/autorun/photon/cl_photon_hud.lua (hunk 1 above)
Comment (DBotThePony) [reply lua/autorun/photon/cl_photon_hud.lua]: I did this to not to call :BuildCode() when :Init() has not been called. If it is safe to :BuildCode() each time, then i can remove that check

**Review by JoshPiper — APPROVED** [review]
